#!/usr/bin/python3
#-*- coding: utf-8 -*-
import http.server
from class_light import Light
from class_http import Handler_http

try:
	server = http.server.HTTPServer(("", 8080), Handler_http)
	print ("started httpserver...")
	server.serve_forever()
except KeyboardInterrupt:
	print ("^C received, shutting down server")
	server.socket.close()